all:
    g++ -I../headers -I/srv/smb/libsml.git/sml/include -L/srv/smb/libsml.git/sml/lib main.cpp hdlc.cpp aes_cmac.cpp crc.cpp RS232.cpp lmnsubscriber.cpp lmnadmin.cpp sendobject.cpp sml.cpp server.cpp sym.cpp tls.cpp timer.cpp fakeRS232.cpp testZaehler.cpp -lwolfssl -lsml -luuid
